"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

from environ import Env

# -- Environments and paths

env = Env()
BASE_DIR = Path(__file__).resolve().parent

DEBUG = env.bool("DJANGO_DEBUG", default=True)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

STATIC_URL = "static/"


# -- Application components

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",  # for PointField form field.
    "django.contrib.postgres",  # for ArrayField.
    "gisserver",  # the django-gisserver app
    "places",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# -- Security

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "SECRET_KEY", default="django-insecure-_=n*h+nd3ty@7)w#1kn_8ohdge3be*v19#wvv-h)@5_sam)$6b"
)


# -- Internationalization

LANGUAGE_CODE = "en-us"
TIME_ZONE = env.str("TIME_ZONE", default="Europe/Amsterdam")
USE_I18N = True
USE_TZ = True


# -- External services

DATABASES = {
    "default": env.db_url(
        "DATABASE_URL",
        default="postgres://localhost/gisserver_example",  # default homebrew user is superuser
        engine="django.contrib.gis.db.backends.postgis",
    )
}

# -- Third party module settings

# As this is an example, we offer to play with the various performance optimization settings:
GISSERVER_USE_DB_RENDERING = env.bool("GISSERVER_USE_DB_RENDERING", default=True)
GISSERVER_CAPABILITIES_BOUNDING_BOX = env.bool("GISSERVER_CAPABILITIES_BOUNDING_BOX", default=True)
GISSERVER_COUNT_NUMBER_MATCHED = env.int("GISSERVER_COUNT_NUMBER_MATCHED", default=1)
