# File format: https://pre-commit.com/#plugins
# Supported hooks: https://pre-commit.com/hooks.html
# Running "make format" fixes most issues for you
default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args:
        - --py310-plus
        - --keep-runtime-typing
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.18.0"
    hooks:
      - id: django-upgrade
        args:
          - --target-version=3.2
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args:
        - --fix
        - --show-fixes
        - --config=pyproject.toml
        - --exit-non-zero-on-fix
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
