---
language: python

dist: bionic
addons:
  postgresql: 10
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libgdal20
      - libproj13  # Fixes projection tests
      - gdal-bin
      - postgresql-10-postgis-2.5
      - postgresql-10-postgis-2.5-scripts
env:
  global:
    - DATABASE_URL=postgresql://postgres@localhost/django-gisserver

# Make sure postgis uses a modern proj library with recent projection transformation parameters
before_install:
  - sudo cp /usr/lib/x86_64-linux-gnu/libproj.so.13.* /usr/lib/x86_64-linux-gnu/libproj.so.12.*
  - sudo systemctl restart postgresql@10-main  # reload for proj13
  - gdalinfo --version
  - psql postgres -c "CREATE EXTENSION IF NOT EXISTS postgis; SELECT PostGIS_full_version();"


matrix:
  include:
    # Python 3.7
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.7
      env: TOXENV=py37-django30
    # Python 3.8
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.8
      env: TOXENV=py38-django30

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -rf $HOME/.cache/pip/log

install:
  - pip install tox codecov

script:
  - tox -e $TOXENV

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
