[tox]
envlist =
    py39-django{32}
    py310-django{42,50}
    py311-django{42,50,51,52}
    py312-django{50,51,52,60}
    py313-django{51,52,60}
    py314-django{52,60}

[testenv]
allowlist_externals = coverage
commands = coverage run --parallel -m pytest {posargs}
deps =
    django32: Django~=3.2
    django42: Django~=4.2
    django50: Django~=5.0
    django51: Django~=5.1
    django52: Django~=5.2
    django60: Django~=6.0
passenv = DATABASE_URL, GISSERVER_USE_DB_RENDERING
extras = test

[testenv:coverage-report]
deps = coverage
skip_install = true
commands =
    coverage combine
    coverage report
